allowBuilds:
  canvas: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@iblai/data-layer@1.9.3'
  - '@iblai/iblai-js@1.26.0'
  - '@iblai/web-containers@1.15.0'
  - '@iblai/web-utils@1.13.0'
